name: Build Cordova Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create myApp com.example.app ShadowOfTheSecondMoon
          cd myApp
          cordova platform add android
          rm -rf www
          cp -r ../www .
          cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
