name: Build Cordova Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create apkbuilder com.yourdomain.game "ShadowOfSecondMoon"
          cd apkbuilder
          cordova platform add android
          rm -rf www
          cp -r ../www .
          cordova build android --no-interactive

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: apkbuilder/platforms/android/app/build/outputs/apk/debug/app-debug.apk
