name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: cordova create myApp com.example.shadowmoon "Shadow Of The Second Moon"

      - name: Copy game files and config.xml
        run: |
          cp -r * myApp/www || true
          cp config.xml myApp/config.xml
          cp icon.png myApp/icon.png

      - name: Change to project directory
        run: cd myApp && cordova platform add android

      - name: Build Android APK
        run: cd myApp && cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Shadow-Of-The-Second-Moon-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
