name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: cordova create myApp com.example.shadowmoon "Shadow Of The Second Moon"

      - name: Copy game files to www
        run: cp -r * myApp/www || true

      - name: Add Android platform
        run: |
          cd myApp
          cordova platform add android

      - name: Create icon folder
        run: mkdir -p myApp/res/icon/android

      - name: Copy custom icon
        run: cp icon.png myApp/res/icon/android/icon-192.png

      - name: Build APK
        run: |
          cd myApp
          cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShadowOfTheSecondMoon-APK
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
