name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create myApp com.example.app "Shadow Of The Second Moon"
          cd myApp
          cordova platform add android

      - name: Copy game files into www folder
        run: |
          shopt -s extglob
          cp -r !(myApp|.git|node_modules|.github) myApp/www/

      - name: Add custom icon
        run: |
          cp icon.png myApp/res/icon/android/icon-192.png

      - name: Build APK
        run: |
          cd myApp
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ShadowOfTheSecondMoon-APK
          path: myApp/platforms/android/app/build/outputs/apk/release/app-release.apk
